from typing import Any, Protocol

from app.engine.simulation_context import LifeState, YearResult
from app.modules.timeline.models import LifeEventLog, LifeSaveRecord, LifeYearSnapshot, TimelineEntry


class SaveRepository(Protocol):
    def save_record(self, record: LifeSaveRecord) -> None: ...

    def get_record(self, life_id: str) -> LifeSaveRecord | None: ...

    def list_records(self) -> list[LifeSaveRecord]: ...

    def save_state(self, state: LifeState) -> None: ...

    def get_state(self, life_id: str) -> LifeState: ...

    def state_exists(self, life_id: str) -> bool: ...

    def append_year_result(self, result: YearResult) -> None: ...

    def get_year_results(self, life_id: str) -> list[YearResult]: ...

    def get_year_result_by_age(self, life_id: str, age: int) -> YearResult | None: ...

    def append_snapshot(self, snapshot: LifeYearSnapshot) -> None: ...

    def get_snapshots(self, life_id: str) -> list[LifeYearSnapshot]: ...

    def get_snapshot_by_age(self, life_id: str, age: int) -> LifeYearSnapshot | None: ...

    def append_event_logs(self, life_id: str, logs: list[LifeEventLog]) -> None: ...

    def get_event_logs(
        self,
        life_id: str,
        *,
        age_min: int | None = None,
        age_max: int | None = None,
        event_category: str | None = None,
    ) -> list[LifeEventLog]: ...

    def append_timeline_entries(self, life_id: str, entries: list[TimelineEntry]) -> None: ...

    def get_timeline_entries(
        self,
        life_id: str,
        *,
        age_min: int | None = None,
        age_max: int | None = None,
        entry_type: str | None = None,
    ) -> list[TimelineEntry]: ...

    def save_inheritance(self, life_id: str, result: dict[str, Any]) -> None: ...

    def get_inheritance(self, life_id: str) -> dict[str, Any]: ...

    def save_heir_continuation(self, source_life_id: str, record: dict[str, Any]) -> None: ...

    def get_heir_continuation(self, source_life_id: str) -> dict[str, Any] | None: ...
